### PR TITLE
fix: use correct highlight offset even when rootDir is not root package directory

### PR DESCRIPTION
**Pull request by wilsonparson**
When a Jest config's `rootDir` is not the same directory as the root package directory (e.g., a monorepo with local Jest configs for each library or app), the highlight offset is calculated incorrectly because it assumes `rootDir` is the root directory of the package. This only occurs when the `filePath` is not truncated (i.e., does not have a leading `'...'`):

incorrect-offset

This PR updates the offset calculation to rely on `rawPath` and `filePath` instead of `rootDir` to provide a consistent highlight offset regardless of `rootDir`'s location:

correct-offset

The PR includes three commits:
1. 3 passing tests and 1 failing test to document the bug
2. The fix (4 passing tests)
3. A refactor of the `highlight` function, removing the `rootDir` parameter since it is no longer being used

### CODE REVIEW

**Comment by SimenB** [comment]
Do we do any `rootDir` replacement? If not this makes sense to me

**Comment by wparsonest** [comment]
Just commenting to see if we can keep things moving on this!

**Comment by SimenB** [comment]
@jeysal @thymikee should we land this?

**Comment by jeysal** [comment]
:+1:

**Review by thymikee — APPROVED** [review]
LGTM. If it breaks a use case we're not aware of, we can then add another test and make it work for both cases

**Comment by joshdegouveia** [comment]
@wilsonparson I ran into this same issue while attempting to add `jest-watch-typeahead` to a monorepo. Would you mind if I forked your repo and fixed conflicts so that this PR could be merged? Or give me write permissions to your repo?

**Comment by wilsonparson** [comment]
@joshdegouveia thanks for the nudge! I just resolved the conflicts. Hopefully this fix resolves the issue you're having as well!

**Comment by joshdegouveia** [comment]
@jeysal @SimenB @thymikee bumping this 🙂

**Comment by jeysal** [comment]
This may have caused https://github.com/jest-community/jest-watch-typeahead/issues/46

**Pull request merged**
